apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-rollout.fullname" . }}-stable
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-rollout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  {{- with .Values.service.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPortName }}
      protocol: TCP
      name: {{ .Values.service.containerPortName }}
      {{- with .Values.service.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
  selector:
    {{- include "generic-rollout.selectorLabels" . | nindent 4 }}