{{- if .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "generic-rollout.fullname" . }}-gateway
  namespace: {{ .Values.istio.gateway.namespace }}
  labels:
    {{- include "generic-rollout.labels" . | nindent 4 }}
    {{- with .Values.istio.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.istio.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- toYaml .Values.istio.gateway.selector | nindent 4 }}
  servers:
    {{- toYaml .Values.istio.gateway.servers | nindent 4 }}
{{- end }}