{{- if and .Values.istio.externalServices.enabled .Values.istio.externalServices.jsonplaceholder.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ .Values.istio.externalServices.jsonplaceholder.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-rollout.labels" . | nindent 4 }}
    {{- with .Values.istio.externalServices.jsonplaceholder.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  hosts:
    {{- toYaml .Values.istio.externalServices.jsonplaceholder.hosts | nindent 4 }}
  ports:
    {{- toYaml .Values.istio.externalServices.jsonplaceholder.ports | nindent 4 }}
  resolution: {{ .Values.istio.externalServices.jsonplaceholder.resolution }}
  location: {{ .Values.istio.externalServices.jsonplaceholder.location }}
---
{{- if .Values.istio.externalServices.jsonplaceholder.destinationRule.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.istio.externalServices.jsonplaceholder.destinationRule.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-rollout.labels" . | nindent 4 }}
    {{- with .Values.istio.externalServices.jsonplaceholder.destinationRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: {{ .Values.istio.externalServices.jsonplaceholder.destinationRule.host }}
  trafficPolicy:
    {{- toYaml .Values.istio.externalServices.jsonplaceholder.destinationRule.trafficPolicy | nindent 4 }}
{{- end }}
{{- end }}