apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: circuit-breaker-state
  namespace: {{ .Release.Namespace }}
spec:
  args:
  - name: rollout-pod-hash
  metrics:
  - name: cb-state
    interval: 15s
    initialDelay: 5s
    count: 3
    successCondition: "result[0] != 1"
    failureLimit: 1

    provider:
      prometheus:
        address: "{{ .Values.rollout.analysisTemplate.prometheus.address }}"
        timeout: 10

        query: |
          circuit_breaker_external_api_state{
            namespace="{{ .Release.Namespace }}",
            job="{{ include "generic-rollout.fullname" . }}",
            pod=~".*-{{ "{{" }}args.rollout-pod-hash{{ "}}" }}-[a-z0-9]+",
          }