apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: external-api-success-rate
  namespace: {{ .Release.Namespace }}
spec:
  args:
  - name: rollout-pod-hash

  metrics:
  - name: external-api-success-rate
    interval: 20s
    initialDelay: 10s
    count: 3
    successCondition: "result[0] >= 0.98"
    failureLimit: 2
    provider:
      prometheus:
        address: "{{ .Values.rollout.analysisTemplate.prometheus.address }}"
        timeout: 10

        query: |
          sum(rate(http_client_external_api_requests_total{
            namespace="{{ .Release.Namespace }}",
            job="{{ include "generic-rollout.fullname" . }}",
            pod=~".*-{{ "{{" }}args.rollout-pod-hash{{ "}}" }}-[a-z0-9]+", 
            status="success"
          }[1m]))
          /
          sum(rate(http_client_external_api_requests_total{
            namespace="{{ .Release.Namespace }}",
            job="{{ include "generic-rollout.fullname" . }}",
            pod=~".*-{{ "{{" }}args.rollout-pod-hash{{ "}}" }}-[a-z0-9]+", 
          }[1m]))