apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: general-success-rate
  namespace: {{ .Release.Namespace }}
spec:
  args:
  - name: rollout-pod-hash

  metrics:
  - name: success-rate
    interval: 20s
    initialDelay: 10s
    count: 3
    successCondition: "result[0] >= 0.99"
    failureLimit: 2

    provider:
      prometheus:
        address: "{{ .Values.rollout.analysisTemplate.prometheus.address }}"
        timeout: 10

        query: |
          sum(rate(http_requests_total{
            namespace="{{ .Release.Namespace }}",
            job="{{ include "generic-rollout.fullname" . }}",
            pod=~".*-{{ "{{" }}args.rollout-pod-hash{{ "}}" }}-[a-z0-9]+",
            status=~"2..|3.."
          }[1m]))
          /
          sum(rate(http_requests_total{
            namespace="{{ .Release.Namespace }}",
            job="{{ include "generic-rollout.fullname" . }}",
            pod=~".*-{{ "{{" }}args.rollout-pod-hash{{ "}}" }}-[a-z0-9]+",
          }[1m]))